baseurl = "https://daybook.biz"
languageCode = "ja"
Title = "電脳業務日誌"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; 2008-2019 mzch"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "mzch"
  facebook = "kch.matsumoto"
  instagram = "mzch"
  github = "mzch"
  vimeo = "letlive"
  linkedin = "letlive"
  # Disqus shortname
  disqus = "daybook-biz"
  # Google Analytics API key.
  ga_api_key = "UA-12204411-1"
  # Logo image. This is displayed ogp image.
  #logo = "/img/logo.png"
  #favicon = "/img/favicon.ico"

[[menu.main]]
    name = "Post"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 4

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
